spring.application.name=demoDataMongo
spring.mongodb.uri=mongodb://newuser:password@localhost:27017/test?authSource=test
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.web.error.include-binding-errors=always
spring.web.error.include-message=always