spring.application.name=demoDataJdbc
spring.datasource.url=jdbc:h2:mem:example
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Enabling H2 Console
spring.h2.console.enabled=true
